//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorAlmacen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public int audit_id { get; set; }
        public string table_name { get; set; }
        public string record_id { get; set; }
        public string action { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.DateTime> change_date { get; set; }
        public string old_value { get; set; }
        public string new_value { get; set; }
    }
}
