//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorAlmacen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Areas = new HashSet<Area>();
            this.Products = new HashSet<Product>();
        }
    
        public int category_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public bool is_active { get; set; }
        public System.DateTime created_at { get; set; }
    
        public virtual ICollection<Area> Areas { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
