//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorAlmacen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movement
    {
        public Movement()
        {
            this.MovementDetails = new HashSet<MovementDetail>();
        }
    
        public int movement_id { get; set; }
        public string folio { get; set; }
        public string movement_type { get; set; }
        public string status { get; set; }
        public System.DateTime movement_date { get; set; }
        public int user_id { get; set; }
        public string comment { get; set; }
    
        public virtual ICollection<MovementDetail> MovementDetails { get; set; }
        public virtual User User { get; set; }
    }
}
