//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorAlmacen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.MovementDetails = new HashSet<MovementDetail>();
            this.Stocks = new HashSet<Stock>();
        }
    
        public int product_id { get; set; }
        public string sku { get; set; }
        public string name { get; set; }
        public int category_id { get; set; }
        public bool is_active { get; set; }
        public Nullable<int> reorder_threshold { get; set; }
        public System.DateTime created_at { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<MovementDetail> MovementDetails { get; set; }
        public virtual ICollection<Stock> Stocks { get; set; }
    }
}
