//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorAlmacen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int stock_id { get; set; }
        public int product_id { get; set; }
        public int area_id { get; set; }
        public int quantity { get; set; }
        public System.DateTime last_update { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Product Product { get; set; }
    }
}
