//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorAlmacen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Movements = new HashSet<Movement>();
        }
    
        public int user_id { get; set; }
        public string username { get; set; }
        public string password_hash { get; set; }
        public string display_name { get; set; }
        public string role { get; set; }
        public bool is_active { get; set; }
        public System.DateTime created_at { get; set; }
    
        public virtual ICollection<Movement> Movements { get; set; }
    }
}
